from pathlib import Path
import zipfile
out=Path("/mnt/data/MashMac_perfect_starter"); out.mkdir(exist_ok=True)
files={
"index.html":"""<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>MashMac</title><link rel="stylesheet" href="style.css"></head><body><header><b>☁️ MashMac</b><button id="logout" hidden>Log out</button></header><main><section id="auth"><h1 id="title">Welcome to MashMac</h1><input id="email" type="email" placeholder="Email"><input id="password" type="password" placeholder="Password (6+ characters)"><button id="mainBtn">Create account</button><button id="toggle">Already have an account? Log in</button><p id="authMsg"></p></section><section id="app" hidden><h1>My Videos</h1><label class="upload">＋ Upload video<input id="file" type="file" accept="video/*" hidden></label><p id="status"></p><div id="gallery"></div></section></main><script src="https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2"></script><script src="app.js"></script></body></html>""",
"style.css":"""body{font-family:system-ui;margin:0;background:#f4f7fb;color:#111827}header{background:#111827;color:white;padding:20px;display:flex;justify-content:space-between;font-size:22px}main{max-width:800px;margin:auto;padding:25px}section{background:white;padding:25px;border-radius:18px;margin-top:30px}input{display:block;width:100%;box-sizing:border-box;padding:13px;margin:10px 0;border:1px solid #ccd5e1;border-radius:10px;font-size:16px}button,.upload{display:inline-block;padding:12px 16px;border:0;border-radius:10px;background:#2563eb;color:white;font-weight:700;margin:5px;cursor:pointer}#toggle{background:none;color:#2563eb}.video{background:#fff;margin:15px 0;padding:10px;border-radius:14px}.video video{width:100%;max-height:500px;background:#000}.delete{background:#b91c1c}p{min-height:22px}""",
"app.js":"""const SUPABASE_URL="https://xufqrewcdzwrxsplmyob.supabase.co";const SUPABASE_PUBLISHABLE_KEY="PASTE_YOUR_CURRENT_PUBLISHABLE_KEY_HERE";const BUCKET="mashmac";const sb=window.supabase.createClient(SUPABASE_URL,SUPABASE_PUBLISHABLE_KEY);let signup=true;const $=x=>document.getElementById(x);function say(x,t,ok=false){$(x).textContent=t;$(x).style.color=ok?"green":"crimson"}$("toggle").onclick=()=>{signup=!signup;$("title").textContent=signup?"Welcome to MashMac":"Welcome back";$("mainBtn").textContent=signup?"Create account":"Log in";$("toggle").textContent=signup?"Already have an account? Log in":"Need an account? Sign up"};$("mainBtn").onclick=async()=>{if(SUPABASE_PUBLISHABLE_KEY.includes("PASTE_"))return say("authMsg","Add your Publishable key to app.js first.");let e=$("email").value.trim(),p=$("password").value;if(!e)return say("authMsg","Enter your email.");if(p.length<6)return say("authMsg","Password must be at least 6 characters.");$("mainBtn").disabled=true;let r=signup?await sb.auth.signUp({email:e,password:p}):await sb.auth.signInWithPassword({email:e,password:p});$("mainBtn").disabled=false;if(r.error)return say("authMsg",r.error.message);if(signup&&!r.data.session)return say("authMsg","Account created. Check your email, then log in.",true);showApp()};async function showApp(){$("auth").hidden=true;$("app").hidden=false;$("logout").hidden=false;await load()}function showAuth(){$("auth").hidden=false;$("app").hidden=true;$("logout").hidden=true}$("logout").onclick=async()=>{await sb.auth.signOut();showAuth()};$("file").onchange=async()=>{let f=$("file").files[0];if(f)await upload(f)};async function upload(f){let {data:{user}}=await sb.auth.getUser();if(!user)return;let path=user.id+"/"+Date.now()+"_"+f.name.replace(/[^a-zA-Z0-9._-]/g,"_");say("status","Uploading...");let r=await sb.storage.from(BUCKET).upload(path,f,{contentType:f.type});if(r.error)return say("status",r.error.message);say("status","Upload complete.",true);load()}async function load(){let {data:{user}}=await sb.auth.getUser();if(!user)return;let r=await sb.storage.from(BUCKET).list(user.id,{limit:100});if(r.error)return say("status",r.error.message);$("gallery").innerHTML="";for(let x of r.data){let path=user.id+"/"+x.name;let u=sb.storage.from(BUCKET).getPublicUrl(path).data.publicUrl;let d=document.createElement("div");d.className="video";d.innerHTML="<video controls src='"+u+"'></video><b>"+x.name+"</b>";let b=document.createElement("button");b.className="delete";b.textContent="Delete";b.onclick=async()=>{let z=await sb.storage.from(BUCKET).remove([path]);if(z.error)say("status",z.error.message);else load()};d.appendChild(b);$("gallery").appendChild(d)}}sb.auth.getSession().then(x=>x.data.session?showApp():showAuth());"""
}
for n,c in files.items(): (out/n).write_text(c,encoding="utf-8")
zip_path="/mnt/data/MashMac_perfect_starter.zip"
with zipfile.ZipFile(zip_path,"w",zipfile.ZIP_DEFLATED) as z:
    for p in out.iterdir(): z.write(p,p.name)
print(zip_path)

